"""remove author_id from Article

Revision ID: ca172b69a5f1
Revises: ecb0dba6f31b
Create Date: 2025-07-10 14:39:20.462539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca172b69a5f1'
down_revision: Union[str, Sequence[str], None] = 'ecb0dba6f31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['owner_id'], ['id'])
    op.drop_column('articles', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'owner_id')
    # ### end Alembic commands ###
